nodeLinker: node-modules
enableScripts: false
enableGlobalCache: true

catalog:
  "@effect/atom-react": 4.0.0-beta.59
  "@effect/language-service": 0.84.2
  "@effect/openapi-generator": 4.0.0-beta.59
  "@effect/platform-node": 4.0.0-beta.59
  "@effect/platform-node-shared": 4.0.0-beta.59
  "@effect/vitest": 4.0.0-beta.59
  "@pierre/diffs": 1.5.1
  "@types/node": 26.6.3
  effect: 4.0.0-beta.59
  tsdown: 0.22.14
  typescript: ^5.9.3
  vite: 8.3.1
  vitest: 5.0.2

packageExtensions:
  "@effect/platform-node@*":
    peerDependenciesMeta:
      ioredis:
        optional: true
  "@lexical/yjs@*":
    peerDependenciesMeta:
      yjs:
        optional: true
  "app-builder-lib@*":
    peerDependenciesMeta:
      electron-builder-squirrel-windows:
        optional: true
