nodeLinker: node-modules
enableScripts: false
enableGlobalCache: true

catalog:
  "@effect/atom-react": 4.0.0-beta.59
  "@effect/language-service": 0.84.2
  "@effect/openapi-generator": 4.0.0-beta.59
  "@effect/platform-node": 4.0.0-beta.59
  "@effect/platform-node-shared": 4.0.0-beta.59
  "@effect/vitest": 4.0.0-beta.59
  "@pierre/diffs": 1.1.20
  "@types/node": 24.12.0
  effect: 4.0.0-beta.59
  tsdown: 0.22.0
  typescript: ^5.7.3
  vitest: 4.1.10

packageExtensions:
  "@effect/platform-node@*":
    peerDependenciesMeta:
      ioredis:
        optional: true
  "@pierre/diffs@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "@lexical/yjs@*":
    peerDependenciesMeta:
      yjs:
        optional: true
  "app-builder-lib@*":
    peerDependenciesMeta:
      electron-builder-squirrel-windows:
        optional: true
