// @effect-diagnostics nodeBuiltinImport:off
import { createHash, timingSafeEqual } from "node:crypto";

import * as Effect from "effect/Effect";
import * as SqlClient from "effect/unstable/sql/SqlClient";

const SHA256_HEX_PATTERN = /^[0-9a-f]{64}$/u;

interface AttachmentContentCommitmentRow {
  readonly attachmentId: string;
  readonly contentSha256: string;
  readonly sizeBytes: number;
}

export function computeAttachmentContentSha256(bytes: Uint8Array): string {
  return createHash("sha256").update(bytes).digest("hex");
}

/**
 * Persist the immutable byte commitment before a normalized attachment can
 * enter orchestration. `attachment_id` is generated by Cafe, and INSERT (rather
 * than UPSERT) makes even an astronomically unlikely id collision fail closed
 * instead of changing the identity of an existing stored file.
 */
export const insertAttachmentContentCommitment = Effect.fn("insertAttachmentContentCommitment")(
  function* (input: {
    readonly sql: SqlClient.SqlClient;
    readonly attachmentId: string;
    readonly threadId: string;
    readonly contentSha256: string;
    readonly sizeBytes: number;
  }) {
    yield* input.sql`
    INSERT INTO attachment_content_commitments (
      attachment_id,
      thread_id,
      content_sha256,
      size_bytes
    ) VALUES (
      ${input.attachmentId},
      ${input.threadId},
      ${input.contentSha256},
      ${input.sizeBytes}
    )
  `;
  },
);

/**
 * Compare two server-recorded upload commitments without returning either
 * digest to callers. Missing/legacy rows, cross-thread rows, malformed rows,
 * and inconsistent sizes all fail closed.
 */
export const haveSameAttachmentContent = Effect.fn("haveSameAttachmentContent")(function* (
  sql: SqlClient.SqlClient,
  input: {
    readonly threadId: string;
    readonly originalAttachmentId: string;
    readonly originalSizeBytes: number;
    readonly retryAttachmentId: string;
    readonly retrySizeBytes: number;
  },
) {
  const rows = yield* sql<AttachmentContentCommitmentRow>`
    SELECT
      attachment_id AS "attachmentId",
      content_sha256 AS "contentSha256",
      size_bytes AS "sizeBytes"
    FROM attachment_content_commitments
    WHERE thread_id = ${input.threadId}
      AND attachment_id IN (${input.originalAttachmentId}, ${input.retryAttachmentId})
    ORDER BY attachment_id ASC
  `;
  if (rows.length !== (input.originalAttachmentId === input.retryAttachmentId ? 1 : 2)) {
    return false;
  }

  const originalCommitment = rows.find((row) => row.attachmentId === input.originalAttachmentId);
  const retryCommitment = rows.find((row) => row.attachmentId === input.retryAttachmentId);
  if (
    originalCommitment === undefined ||
    retryCommitment === undefined ||
    originalCommitment.sizeBytes !== input.originalSizeBytes ||
    retryCommitment.sizeBytes !== input.retrySizeBytes ||
    !SHA256_HEX_PATTERN.test(originalCommitment.contentSha256) ||
    !SHA256_HEX_PATTERN.test(retryCommitment.contentSha256)
  ) {
    return false;
  }

  return timingSafeEqual(
    Buffer.from(originalCommitment.contentSha256, "hex"),
    Buffer.from(retryCommitment.contentSha256, "hex"),
  );
});
