// This file is generated by the effect-acp package. Do not edit manually.
// ACP schema release: v0.11.3 (e87bde7322ceb8d52d9e81718f5783beb66f9f6d)
// schema.unstable.json sha256: 1ceeff8f64fd750688f98ea13099436a908012866f2343698f6a9ac85a652bb0
// meta.unstable.json sha256: ebdaf23edddbd6865e41e4d233136c56573344d6cd657d41144fe32dacc6dbaa

export const AGENT_METHODS = {
  authenticate: "authenticate",
  initialize: "initialize",
  logout: "logout",
  session_cancel: "session/cancel",
  session_close: "session/close",
  session_fork: "session/fork",
  session_list: "session/list",
  session_load: "session/load",
  session_new: "session/new",
  session_prompt: "session/prompt",
  session_resume: "session/resume",
  session_set_config_option: "session/set_config_option",
  session_set_mode: "session/set_mode",
  session_set_model: "session/set_model",
} as const;

export const CLIENT_METHODS = {
  fs_read_text_file: "fs/read_text_file",
  fs_write_text_file: "fs/write_text_file",
  session_elicitation: "session/elicitation",
  session_elicitation_complete: "session/elicitation/complete",
  session_request_permission: "session/request_permission",
  session_update: "session/update",
  terminal_create: "terminal/create",
  terminal_kill: "terminal/kill",
  terminal_output: "terminal/output",
  terminal_release: "terminal/release",
  terminal_wait_for_exit: "terminal/wait_for_exit",
} as const;

export const PROTOCOL_VERSION = 1 as const;
